apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: config-irsa
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/unbounded-tech/config-irsa
    meta.crossplane.io/description: A Configuration package that defines hops's `IRSA` installation.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: ">=v1.0.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.0.2"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam
    version: ">=v2.1.1"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.5.1"
