apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: aws-irsa
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott <pat@patscott.io>
    meta.crossplane.io/source: github.com/hops-ops/aws-irsa
    meta.crossplane.io/description: Configures IAM Roles for Service Accounts (IRSA) on EKS clusters.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam
    version: ">=v2.3.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
