apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-irsa
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/configuration-aws-irsa
    meta.crossplane.io/description: A Configuration package that defines hops's `IRSA` installation.
spec:
  dependsOn:
  - provider: ghcr.io/crossplane-contrib/provider-family-aws
    version: ">=v2.2.0"
  - provider: ghcr.io/crossplane-contrib/provider-aws-iam
    version: ">=v2.2.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.5.1"
