apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: config-irsa
spec:
  package: ghcr.io/hops-ops/config-irsa:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}

---

# skipDependencyResolution false would have named this hops-ops-config-irsarender
# so we need to match that format to avoid issues with the package name
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-config-irsarender
spec:
  package: ghcr.io/hops-ops/config-irsa_render:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}
