name: on-pr

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  id-token: write
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.12.2
    with:
      examples: |
        [
          { "example": "examples/irsas/minimal.yaml" },
          { "example": "examples/irsas/standard.yaml" }
        ]
      api_path: apis/irsas
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.12.2

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.12.2
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.12.2
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
