name: pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v0.4.2
    with:
      examples: |
        [
          "examples/irsas/example.yaml",
          "examples/irsas/example-minimal.yaml"
        ]
      api_path: apis/irsas
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v0.4.2

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v0.4.2
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
