name: on-push-main
on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:

  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.5.1
    with:
      examples: |
        [
          { "example": "examples/irsas/minimal.yaml" },
          { "example": "examples/irsas/standard.yaml" }
        ]
      api_path: apis/irsas
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.5.1

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.5.1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.1
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""
